site_name: Projeto D32
nav: 
  - Home: index.md
  - Planejamento: planejamento.md
  - Design: 
    - Design do Jogo: designjogo.md
    - Introspecção: introspeccao.md
    - Metas de Usabilidade: metasusabilidade.md
    - Questionário: questionario.md
    - Avaliações:
        - Planejamento de Avaliações: planejamento-avaliacao.md
    - Storyboards: storyboards.md
  - Apresentações:
    - Apresentação 1: "https://youtu.be/VJKBLy3pV18"
    - Apresentação 2: "https://youtu.be/cZw_swA9SoE"
    - Apresentação 3: "https://youtu.be/YQc2XZZL1PQ"
    - Apresentação 4: "https://youtu.be/p87Ak-Exb6Y"

theme: 
  name: material
  language: "pt"
  palette:
    primary: "deep purple"
    secondary: "indigo"

repo_name: "D32 Documents"
repo_url: "https://github.com/Design-de-Jogos/2020.1-MobileAccessibility"
