site_name: Projeto 32b
nav: 
  - Home: index.md
  - Planejamento: planejamento.md
  - Design do Jogo: designjogo.md
  - Introspecção: instrospeccao.md
  - Metas de Usabilidade: metasusabilidade.md

theme: 
  name: material
  language: "pt"
  palette:
    primary: "deep purple"
    secondary: "indigo"

repo_name: "32b Documents"
repo_url: "https://github.com/Design-de-Jogos/2020.1-MobileAccessibility"
