site_name: Projeto D32
nav: 
  - Home: index.md
  - Planejamento: planejamento.md
  - Design do Jogo: designjogo.md
  - Introspecção: introspeccao.md
  - Metas de Usabilidade: metasusabilidade.md
  - Questionário: questionario.md
  - Apresentações:
    - Ap1: "https://github.com/Design-de-Jogos/2020.1-MobileAccessibility"
    - Ap2: "https://github.com/Design-de-Jogos/2020.1-MobileAccessibility"
    - Ap3: "https://github.com/Design-de-Jogos/2020.1-MobileAccessibility"

theme: 
  name: material
  language: "pt"
  palette:
    primary: "deep purple"
    secondary: "indigo"

repo_name: "D32 Documents"
repo_url: "https://github.com/Design-de-Jogos/2020.1-MobileAccessibility"
