site_name: Projeto D32
nav: 
  - Home: index.md
  - Planejamento: planejamento.md
  - GDD: designjogo.md
  - TDD: tdd.md
  - Desenvolvimento: 
    - Introspecção: introspeccao.md
    - Metas de Usabilidade: metasusabilidade.md
    - Questionário: questionario.md
    - Avaliações:
        - Planejamento de Avaliações: planejamento-avaliacao.md
        - Resultados: resultados.md
    - Storyboards: storyboards.md
    - Protótipo de Alta Fidelidade: protalta.md
    - Protótipo de Baixa Fidelidade: protbaixa.md
  - Apresentações e Extra:
    - Apresentação 1: "https://youtu.be/VJKBLy3pV18"
    - Apresentação 2: "https://youtu.be/cZw_swA9SoE"
    - Apresentação 3: "https://youtu.be/YQc2XZZL1PQ"
    - Apresentação 4: "https://youtu.be/p87Ak-Exb6Y"
    - Protótipo Interativo: "https://www.figma.com/proto/7jHkaW8AplksTso9M2fXff/Prot%C3%B3tipo-D32?node-id=4%3A71&scaling=min-zoom"

theme: 
  name: material
  language: "pt"
  palette:
    primary: "deep purple"
    secondary: "indigo"

repo_name: "D32 Documents"
repo_url: "https://github.com/Design-de-Jogos/2020.1-MobileAccessibility"
