site_name: Projeto 32b
nav: 
  - Home: index.md
  - Planejamento: planejamento.md
  - Design do Jogo: designjogo.md

theme: 
  name: material
  language: "pt"
  palette:
    primary: "deep purple"
    secondary: "indigo"
